apiVersion: v1
kind: Service
metadata:
  name: postgres18-service
  namespace: database
spec:
  selector:
    app: postgres18
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30440  # optional, only for NodePort
  type: NodePort